orbs:

  docker: circleci/docker@1.7.0

workflows:

    example-workflow:

      jobs:

        - docker/publish:

            docker-password: aricrew123 

            docker-username: aricrew 

            image: ari 

            use-remote-docker: true 
